### ISSUE TITLE
Failure within UITableViewCell and possibly UICollectionViewCell

### ISSUE THREAD

**Issue by simonrowlands** [novoda/novoda-constraints#22]
Currently the library fails when applying within a table cell, this is due to the fact that we are setting the `contentView` of the cell to have translatesAutoresizingMaskIntoConstraints = false which is WRONG.
The cell content view and the root view of the screen should never have this set to false.

The root view of the screen is currently being caught via "if view.superview != nil" but the cell content view does have a superview and therefore is not being caught.

I really don't want to check if the superview is a table/collection cell; can we find a way of catching this?

**Comment by juankysoriano** [comment]
Closing as this repository is no longer under maintenance and it's about to be archived
